"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const typeorm_1 = require("./typeorm");
exports.AccountsTypeorm = typeorm_1.AccountsTypeorm;
const User_1 = require("./entity/User");
exports.User = User_1.User;
const UserEmail_1 = require("./entity/UserEmail");
exports.UserEmail = UserEmail_1.UserEmail;
const UserService_1 = require("./entity/UserService");
exports.UserService = UserService_1.UserService;
const UserSession_1 = require("./entity/UserSession");
exports.UserSession = UserSession_1.UserSession;
const entities = [User_1.User, UserEmail_1.UserEmail, UserService_1.UserService, UserSession_1.UserSession];
exports.entities = entities;
exports.default = typeorm_1.AccountsTypeorm;
